openapi: 3.2.0
info:
  title: Reflect Tests API
  version: 1.0.0
  description: 'Effortlessly create, execute, and troubleshoot automated end-to-end tests

    using Reflect''s advanced AI capabilities.'
servers:
- url: https://api.reflect.run/v1
security:
- ApiKeyAuth: []
tags:
- name: Tests
paths:
  /tests:
    get:
      summary: List All Tests
      responses:
        '200':
          description: A list of test descriptions
          content:
            application/json:
              schema:
                type: object
                properties:
                  tests:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        created:
                          type: integer
                        tags:
                          type: array
                          items:
                            type: string
      tags:
      - Tests
      operationId: getTests
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
